### ISSUE TITLE
请教huber，这个咋用，没看到轮询访问网站，也没看到用什么提示datacenter出现目标地区，比如tg

### ISSUE THREAD

**Issue by QJM16** [zzp198/IPV6_VPS#1]
RT

**Comment by zzp198** [comment]
这个是用来提示库存剩余的，库存每天北京8点清理过期的VPS，你现在用当然没有内容，你等明天7点55分左右开始跑脚本，然后等就行，出来自己想要的地区后需要自己去页面申请。（懒得自己频繁刷新网页看库存剩余）

**Comment by zzp198** [comment]
库存剩余是直接显示在控制台和语音提示，毕竟就抢一次，而且轮询的很频繁，就没弄tg
